
  environments:
    - staging
    - production
  replicated: true
  fully_replicated: true
  verify_connection: true
  staging:
   slave1:
      host: 
      adapter: mysql2
      username: root
      password: 
      database: rails_app
      reconnect: false
    slave2:
      host:
      adapter: mysql2
      username: root
      password:
      database: rails_app
      reconnect: false
  production:
    slave1:
      host: 
      adapter: mysql2
      username: root
      password: 
      database: rails_app
      reconnect: true
    slave2:
      host:
      adapter: mysql2
      username: root
      password:
      database: rails_app
      reconnect: true
