octopus:
  environments:
    - development
    - production
  replicated: true
  fully_replicated: true
  verify_connection: true
  development:
    slave1:
      host: localhost
      adapter: mysql2
      username: root
      database: filmo_development
    slave2:
      host: localhost
      adapter: mysql2
      username: root
      database: filmo_development
  production:
    slave1:
      host: 
      adapter: mysql2
      username: root
      database: filmo_production
    slave2:
      host:
      adapter: mysql2
      username: root
      database: filmo_production
